### ISSUE TITLE
Feature request: per-profile config settings (for Download folders, theming)

### ISSUE THREAD

**Issue by markstos** [jtyers/qutebrowser-profile#11]
Generally it's desirable to share the same configuration between profiles, but there are some cases where unique config values provide benefits:

 1. *Downloads* folder. For a "work" profile, you may want to downlaods to land in a work-specific downloads directory to comply with a policy that all work-related files are within a work-specific folder.
 2. *Theming*. You might like the status bar colors to be unique per-profile to tell your profiles apart at a glance, especially if you don't have a visible titlebar.

**Comment by markstos** [comment]
## Proposal 1: Put unique CLI lines in `.desktop` files.

Qute already supports `--set OPTION VALUE` to set a temporary value for a given session.

Extend `qutebrowser-profile --new` to accept `--set` args and pass those through to the the `.desktop` files that #10 would generate. Within the `.desktop` files, the argument would be passed through to `qutebrowser` when calling `qutebrowser-profile --load`. 

This would be simple and flexible to implement.

The downside to this approach is that simply calling `qutebrowser --load profile` wouldn't load these configurations. An alternative is to a launcher like `gtk-launch qute-profile.desktop` from the CLI to launch the alternate profile, or use a GUI launcher to select the profile's `.desktop` entry. The README and `--help` can be updated to advise this approach. 

## Workaround

This feature can be manually achieved by hand-editting the `Exec=` line `.desktop` file that `qutebrowser-profile --new` would generate after #10 is merged.  The change is to add `--set` args that will be passed through to `qutebrowser` there.

**Comment by markstos** [comment]
I'm looking at this today.

**Comment by markstos** [comment]
## Proposal 2: Persist per-profile config settings outside of `.desktop` files. 

I've submitted a PR that implements that above proposal. It works, but have a weakness. Perhaps you want to make *several* `.desktop` launcher files for your work profile, such as one for Slack, one for Google Calendar, and one for your work Gmail. With the above approach, all the custom `--set` arguments would need to copied between the various "work" `.desktop` files. This works, but is a pain. 

**An alternative would be save the custom `--set` options to a file when `--new` is called.**  Perhaps under `$XDG_CONFIG_HOME/qutebrowser/$session`

Then the file could be read by `--load`. This way the  per-profile configs would be managed in a single place.

In a simple version, this file might literally contain a series of `--set OPTION VALUE` flags.  `--load` would simply read the file and add the contents to the `qutebrowser` command line.

If you want to edit the args after you call `--new`, you would manually edit the file.

**Comment by markstos** [comment]
The concern raised in Proposal 2 of supporting multiple `.desktop` files per profile can be supported with what was already implemented for Proposal 1.  If you have a generated a `qutebrowser-work.desktop` file using `qutebrowser-profile --new`, you can reference the first desktop entry from the second, like this:

     Exec=gtk-launch qutebrowser-work.desktop https://example.com

That syntax allows you to re-use the command line stored in the `qutebrowser-work.desktop` while launching a custom URL.

**Comment by jtyers** [comment]
Thanks for your work on this @markstos. I've re-implemented `qutebrowser-profile` in Python which solves a few headaches with its implementation. It now passes unrecognised arguments to `qutebrowser` on launch, so that makes `--set` et al possible.
