### ISSUE TITLE
Change default profile position in window title to end rather than beginning

### ISSUE THREAD

**Issue by markstos** [jtyers/qutebrowser-profile#14]
This is related to #13, which discussing customizing the title.

As mentioned there, as the number of window titles grow in a tab set, only the first few characters are visible. It's an important usability feature that the remaining characters are unique. To enable this usability, browsers tend to append the browser name to the end of window titles, not the beginning. Chromium, Firefox and Qutebrowser all behave this way.

The current default behavior goes against this convention by putting "qute [$profile] -" at the  _beginning_ of window titles.

This issue proposes the default should be changed to align with the more usable approach of other browserse and append " - qute [$profile]" to the end of the title instead.

For those who prrefer the current "prepend" behavior, #13 discusses how to override the default behavior of `qutebrowser-profile`.

**Comment by jtyers** [comment]
Yup I agree this should be customisable, and will be much easier to implement now this is a Python script. Let's close this and move the convo to #13 as I think that should be the approach to fix.
