### ISSUE TITLE
Receive output "cannot use --choose with --load" even when not using "--choose"

### ISSUE THREAD

**Issue by mitchellroe** [jtyers/qutebrowser-profile#19]
## Steps to reproduce

```
$ ./qutebrowser-profile --load work
```

## Expected results

qutebrowser launches with my work profile.

## Actual results

```
$ ./qutebrowser-profile --load work
cannot use --choose with --load
```

## Environment information

- Fedora 35, x86_64
- Commit hash: `6b7784a`
- ```
  $ ./qutebrowser-profile --list
  personal
  work
  ```
- Launching shell (just in case it's relevant): zsh

Let me know if there's any other relevant information you would like me to provide.

**Comment by mitchellroe** [comment]
After `git bisect`, here is the commit which introduced the behavior:
```
commit e1bf5946562e563de52c598c71b98ca93ca10778
Author: jtyers <jtyers@users.noreply.github.com>
Date:   Tue Jul 14 12:05:09 2020 +0100

    feat: default to --choose if nothing selected; add URL as message if running rofi; use $HOME to find profiles, not /run

 qutebrowser-profile | 42 +++++++++++++++++++++++++++++++-----------
 1 file changed, 31 insertions(+), 11 deletions(-)
```

**Comment by OzPineapple** [comment]
Have you updated this to the AUR? I have the same issue and I just installed the package today. I have to use --new in order to access to the profiles

**Comment by jtyers** [comment]
Hi folks, apologies for the slow response to this. `qutebrowser-profile` is now re-implemented in Python, a longed for wishlist item of mine. As a result this should no longer be an issue.
